# https://github.com/catppuccin/starship/blob/main/themes/mocha.toml
palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# https://starship.rs/config
add_newline = "true"

[character]
success_symbol = "[[](green) ❯](green)"
error_symbol = "[[](red) ❯](green)"
vimcmd_symbol = "[ ❮](subtext1)" # For use with zsh-vi-mode

[directory]
read_only = " "
style = "bold green"

[docker_context]
symbol = " "

[git_branch]
symbol = " "
style = "bold mauve"

[git_status]
style = "bold maroon"

[golang]
symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[time]
disabled = false
format = '[\[ $time \]](blue) '
time_format = "%T"
