# https://starship.rs/config

add_newline = true

[conda]
format = '[$symbol$environment](dimmed green) '

[directory]
read_only = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%T"
